export const categoriesSeed = [
  {
    id: 1,
    name: 'Eyeglasses',
    description: 'Classic eyewear crafted for everyday comfort and polished visual clarity.',
    image: 'https://m.media-amazon.com/images/I/71DMLq3uxjL._AC_UY1000_.jpg',
    rating: 4.8,
    discount: 'Up to 45% off',
  },
  {
    id: 2,
    name: 'Sunglasses',
    description: 'UV-protective sunglasses built for bold outdoor style and glare-free comfort.',
    image: 'https://media.istockphoto.com/id/2175168320/photo/sunglasses.jpg?s=612x612&w=0&k=20&c=xdDzvDj4lcqdCjbYXIM6cWdH3M4zyzhCeYlmpd_Kzgc=',
    rating: 4.6,
    discount: 'Up to 60% off',
  },
  {
    id: 3,
    name: 'Contact Lenses',
    description: 'Hydrating daily and monthly contacts for clear vision and all-day comfort.',
    image: 'https://t3.ftcdn.net/jpg/03/34/26/78/360_F_334267828_CfbXnotmqSc4qs2b3J4BcdKm3sIKGj8J.jpg',
    rating: 4.7,
    discount: 'Up to 38% off',
  },
  {
    id: 4,
    name: 'Kids Glasses',
    description: 'Durable kids frames with playful color and flexible comfort for active wear.',
    image: 'https://lenskandy.com/cdn/shop/files/Kids_Black_Flexible_Computer_Glasses_For_Kids_LKEKTR48-RED-15.webp?v=1781180426&width=3840',
    rating: 4.7,
    discount: 'Up to 52% off',
  },
]

export const productsSeed = [
  {
    id: 2,
    name: 'Kepler Classic',
    brand: 'Eagle Eye',
    price: 1499,
    salePrice: 1299,
    rating: 4.7,
    category: 'Eyeglasses',
    badge: 'New',
    image: 'https://media.istockphoto.com/id/1393588108/photo/eyeglasses-in-gray-smoke-bright-color-in-transparent-plastic-eyewear-side-view-with-shadow.jpg?s=612x612&w=0&k=20&c=UAnFAlb8u56nHoTSEUw50JKAXNVtzc7gOtFYqQPtqa4=',
    description: 'A refined matte grey TR90 frame with durable build, soft nose pads and lightweight everyday comfort.',
    material: 'TR90',
    color: 'Midnight Blue',
    lensWidth: '53mm',
    bridgeWidth: '18mm',
    templeLength: '146mm',
    weight: '22g',
    warranty: '2 years',
    priceNote: 'Price may vary based on prescription power and lens choice.',
  },
  {
    id: 4,
    name: 'Astra Minimal',
    brand: 'Eagle Eye',
    price: 1499,
    salePrice: 1299,
    rating: 3.9,
    category: 'Eyeglasses',
    badge: 'Limited',
    image: 'https://m.media-amazon.com/images/I/51WF+viiAnL._AC_UY1100_.jpg',
    description: 'A lightweight rimless titanium frame with polished details, refined shape, and smooth temple fit.',
    material: 'Titanium',
    color: 'Ice Silver',
    lensWidth: '51mm',
    bridgeWidth: '17mm',
    templeLength: '145mm',
    weight: '18g',
    warranty: '2 years',
    priceNote: 'Price may vary based on prescription power and lens choice.',
  },
  {
    id: 5,
    name: 'Orion Vintage',
    brand: 'Eagle Eye',
    price: 1599,
    salePrice: 1399,
    rating: 4.3,
    category: 'Eyeglasses',
    badge: 'Retro',
    image: 'https://thumbs.dreamstime.com/b/elegant-black-gold-modern-stylish-eyewear-frame-high-angle-studio-shot-pair-round-eyeglasses-featuring-acetate-rim-toned-439501121.jpg',
    description: 'A retro round acetate frame with warm walnut tones, sculpted bridge, and classic everyday polish.',
    material: 'Acetate',
    color: 'Walnut',
    lensWidth: '50mm',
    bridgeWidth: '18mm',
    templeLength: '146mm',
    weight: '20g',
    warranty: '2 years',
    priceNote: 'Price may vary based on prescription power and lens choice.',
  },
  {
    id: 6,
    name: 'Nova Edge',
    brand: 'Eagle Eye',
    price: 1699,
    salePrice: 1499,
    rating: 4.5,
    category: 'Eyeglasses',
    badge: 'Best Seller',
    image: 'https://img.muukal.com/goods/1421/black_2.jpg!mk',
    description: 'A sharp gunmetal frame with clean lines, sturdy temple arms, and premium prescription lens support.',
    material: 'Stainless Steel',
    color: 'Gunmetal',
    lensWidth: '54mm',
    bridgeWidth: '17mm',
    templeLength: '148mm',
    weight: '22g',
    warranty: '2 years',
    priceNote: 'Price may vary based on prescription power and lens choice.',
  },
  {
    id: 7,
    name: 'Horizon Frame',
    brand: 'Eagle Eye',
    price: 1399,
    salePrice: 1199,
    rating: 4.0,
    category: 'Eyeglasses',
    badge: 'New',
    image: 'https://img.kwcdn.com/product/fancy/dc191e68-f0a3-41f4-b735-d48d7c24d2c9.jpg',
    description: 'A matte navy semi-rimless frame with low-profile comfort and reliable office-to-evening style.',
    material: 'TR90',
    color: 'Matte Navy',
    lensWidth: '52mm',
    bridgeWidth: '18mm',
    templeLength: '146mm',
    weight: '20g',
    warranty: '2 years',
    priceNote: 'Price may vary based on prescription power and lens choice.',
  },
  {
    id: 8,
    name: 'Cove Artisan',
    brand: 'Eagle Eye',
    price: 1899,
    salePrice: 1699,
    rating: 3.9,
    category: 'Eyeglasses',
    badge: 'Stylish',
    image: 'https://i.ebayimg.com/images/g/wvYAAOSw8ElnxQi~/s-l1200.png',
    description: 'A premium olive marble acetate frame with a soft square profile and refined polished finish.',
    material: 'Acetate',
    color: 'Olive Marble',
    lensWidth: '53mm',
    bridgeWidth: '18mm',
    templeLength: '147mm',
    weight: '23g',
    warranty: '2 years',
    priceNote: 'Price may vary based on prescription power and lens choice.',
  },
  {
    id: 9,
    name: 'Lumen Classic',
    brand: 'Eagle Eye',
    price: 1499,
    salePrice: 1299,
    rating: 4.2,
    category: 'Eyeglasses',
    badge: 'Essential',
    image: 'https://static5.lenskart.com/media/catalog/product/pro/1/thumbnail/1080x1080/9df78eab33525d08d6e5fb8d27136e95//l/i/rose-gold-full-rim-round-lenskart-sg-nuun-lk-e18526af-eyeglasses_243191_dsc2942_11_05_2026.jpg',
    description: 'A sleek stainless steel frame with subtle shine, balanced front profile and everyday wearability.',
    material: 'Flexible Stainless Steel',
    color: 'Satin Black',
    lensWidth: '51mm',
    bridgeWidth: '18mm',
    templeLength: '145mm',
    weight: '19g',
    warranty: '2 years',
    priceNote: 'Price may vary based on prescription power and lens choice.',
  },
  {
    id: 10,
    name: 'Prism Focus',
    brand: 'Eagle Eye',
    price: 1599,
    salePrice: 1399,
    rating: 4.3,
    category: 'Eyeglasses',
    badge: 'Polished',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTFEgooFuFCxNPVL8EPRq2yRXwZ7uP5fHjdWBTmuGPnisPa4eKzMEshju5B&s=10',
    description: 'A polished angular frame with geometric temples, comfortable bridge and sharp visual presence.',
    material: 'Acetate',
    color: 'Greystone',
    lensWidth: '52mm',
    bridgeWidth: '17mm',
    templeLength: '146mm',
    weight: '21g',
    warranty: '2 years',
    priceNote: 'Price may vary based on prescription power and lens choice.',
  },
  {
    id: 11,
    name: 'Solstice Gold',
    brand: 'Eagle Eye',
    price: 2299,
    salePrice: 1999,
    rating: 4.2,
    category: 'Sunglasses',
    badge: 'New Arrival',
    image: 'https://goglassic.com/cdn/shop/files/DSC2190_31c3e717-400d-4383-87d5-d81e0039d85b.png?v=1742467100&width=144',
    description: 'Cat-eye sunglasses with full UV protection, bold mirrored lens styling and refined premium detail.',
    material: 'Titanium',
    color: 'Champagne',
    lensWidth: '55mm',
    bridgeWidth: '20mm',
    templeLength: '140mm',
    weight: '24g',
    warranty: '2 years',
    priceNote: 'Price may vary based on prescription power and lens choice.',
  },
  {
    id: 12,
    name: 'Horizon Shade',
    brand: 'Eagle Eye',
    price: 2399,
    salePrice: 1999,
    rating: 4.2,
    category: 'Sunglasses',
    badge: 'Limited',
    image: 'https://lenskandy.com/cdn/shop/files/SunDrip_Polarised_Bold_Round_Black_Sunglasses_For_Men_Women_LKS5171-BLK-20.webp?v=1780473099&width=3840',
    description: 'A shield-style sunglass with full coverage polarized lenses, sleek black finish and crisp sun clarity.',
    material: 'Stainless Steel',
    color: 'Jet Black',
    lensWidth: '60mm',
    bridgeWidth: '18mm',
    templeLength: '145mm',
    weight: '26g',
    warranty: '2 years',
    priceNote: 'Price may vary based on prescription power and lens choice.',
  },
  {
    id: 13,
    name: 'Nebula Luxe',
    brand: 'Eagle Eye',
    price: 2199,
    salePrice: 1899,
    rating: 4.0,
    category: 'Sunglasses',
    badge: 'Premium',
    image: 'https://images.meesho.com/images/products/529830215/bbtzl_512.webp?width=512',
    description: 'Gradient lens sunglasses with soft acetate frame, warm tortoise tones and glare reducing protection.',
    material: 'Acetate',
    color: 'Tortoise',
    lensWidth: '57mm',
    bridgeWidth: '19mm',
    templeLength: '145mm',
    weight: '25g',
    warranty: '2 years',
    priceNote: 'Price may vary based on prescription power and lens choice.',
  },
  {
    id: 14,
    name: 'Vista Panorama',
    brand: 'Eagle Eye',
    price: 1999,
    salePrice: 1699,
    rating: 3.8,
    category: 'Sunglasses',
    badge: 'Best Seller',
    image: 'https://cdn.fynd.com/v2/falling-surf-7c8bb8/fyprod/wrkr/products/pictures/item/free/original/VI-SG-242-C2/UP21TW3S1r1-C2(01).jpg?dpr=1',
    description: 'A mirrored wrap sunglass with high contrast lenses, sport-ready fit and view-enhancing coverage.',
    material: 'Nylon',
    color: 'Forest Green',
    lensWidth: '58mm',
    bridgeWidth: '19mm',
    templeLength: '149mm',
    weight: '27g',
    warranty: '2 years',
    priceNote: 'Price may vary based on prescription power and lens choice.',
  },
  {
    id: 15,
    name: 'Sierra Fade',
    brand: 'Eagle Eye',
    price: 1899,
    salePrice: 1599,
    rating: 4.7,
    category: 'Sunglasses',
    badge: 'Polarized',
    image: 'https://image.made-in-china.com/202f0j00ghzuisGPulrY/China-Manufacturer-Modern-Circle-Round-Frame-Metal-Thin-Frame-Brown-Pattern-Sunglasses.webp',
    description: 'Retro-inspired round polarized sunglasses with scratch-resistant lenses and premium comfort.',
    material: 'Acetate',
    color: 'Midnight Havana',
    lensWidth: '56mm',
    bridgeWidth: '18mm',
    templeLength: '146mm',
    weight: '24g',
    warranty: '2 years',
    priceNote: 'Price may vary based on prescription power and lens choice.',
  },
  {
    id: 16,
    name: 'Aero Urban',
    brand: 'Eagle Eye',
    price: 2099,
    salePrice: 1799,
    rating: 4.1,
    category: 'Sunglasses',
    badge: 'New',
    image: 'https://www.mvmt.com/dw/image/v2/BDKZ_PRD/on/demandware.static/-/Sites-mgi-master/default/dwfa2bc3c7/images/products/28100281_fr.jpg?sw=1660&sh=1660',
    description: 'A modern geometric sunglass with anti-reflective finish and crisp outdoor clarity.',
    material: 'Stainless Steel',
    color: 'Matte White',
    lensWidth: '59mm',
    bridgeWidth: '19mm',
    templeLength: '145mm',
    weight: '25g',
    warranty: '2 years',
    priceNote: 'Price may vary based on prescription power and lens choice.',
  },
  {
    id: 17,
    name: 'Coastal Breeze',
    brand: 'Eagle Eye',
    price: 2299,
    salePrice: 1999,
    rating: 4.2,
    category: 'Sunglasses',
    badge: 'Limited Edition',
    image: 'https://rukminim3.flixcart.com/image/316/420/xif0q/sunglass/o/7/o/medium-pth01-elligator-original-imahh5yezyayzezv.jpeg?q=90&crop=false',
    description: 'Limited-edition ocean blue sunglasses with bold color, lightweight frame and high UV protection.',
    material: 'Acetate',
    color: 'Oceanic Blue',
    lensWidth: '58mm',
    bridgeWidth: '18mm',
    templeLength: '147mm',
    weight: '26g',
    warranty: '2 years',
    priceNote: 'Price may vary based on prescription power and lens choice.',
  },
  {
    id: 18,
    name: 'Sunset Harbor',
    brand: 'Eagle Eye',
    price: 1799,
    salePrice: 1499,
    rating: 3.9,
    category: 'Sunglasses',
    badge: 'Summer',
    image: 'https://sunglassic.com/cdn/shop/files/IMG_5963_compressed.jpg?v=1683111543&width=2000',
    description: 'A classic aviator sunglass with UV400 lenses, polished metal and timeless everyday wear.',
    material: 'Metal',
    color: 'Matte Gold',
    lensWidth: '57mm',
    bridgeWidth: '19mm',
    templeLength: '146mm',
    weight: '25g',
    warranty: '2 years',
    priceNote: 'Price may vary based on prescription power and lens choice.',
  },
  {
    id: 19,
    name: 'Shadow Storm',
    brand: 'Eagle Eye',
    price: 1999,
    salePrice: 1699,
    rating: 4.4,
    category: 'Sunglasses',
    badge: 'Chic',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSPf9q9TJ32GgxEo1FJs2iQty4QvickxesjS35Ote6mEA&s=10',
    description: 'Oversized urban sunglasses with mirrored lenses, bold black accents and city-ready style.',
    material: 'Acetate',
    color: 'Black',
    lensWidth: '60mm',
    bridgeWidth: '18mm',
    templeLength: '146mm',
    weight: '28g',
    warranty: '2 years',
    priceNote: 'Price may vary based on prescription power and lens choice.',
  },
  {
    id: 20,
    name: 'Glacier Peak',
    brand: 'Eagle Eye',
    price: 2199,
    salePrice: 1999,
    rating: 4.6,
    category: 'Sunglasses',
    badge: 'Explorer',
    image: 'https://www.quay.com/cdn/shop/files/Quay_BigTime_BrushedSilverTan_Front.jpg?v=1773285318&width=450',
    description: 'A sporty wrap sunglass designed for outdoor performance with premium shade and durable nylon.',
    material: 'Nylon',
    color: 'Slate Grey',
    lensWidth: '59mm',
    bridgeWidth: '18mm',
    templeLength: '149mm',
    weight: '27g',
    warranty: '2 years',
    priceNote: 'Price may vary based on prescription power and lens choice.',
  },
  {
    id: 21,
    name: 'Vision Ease',
    brand: 'Eagle Eye',
    price: 299,
    salePrice: 249,
    rating: 3.9,
    category: 'Contact Lenses',
    badge: 'Daily',
    image: 'https://softlenses.in/cdn/shop/files/WhatsAppImage2024-10-26at9.22.35PM_31042336-f636-4b21-98fb-a27674be64f6.jpg?v=1729960677',
    description: 'Daily disposable lenses with gentle hydration, clear vision and easy on/off convenience.',
    material: 'Hydrogel',
    color: 'Clear',
    lensWidth: '14mm',
    bridgeWidth: 'N/A',
    templeLength: 'N/A',
    weight: '6mg',
    warranty: '30-day satisfaction',
    priceNote: 'Price may vary based on prescription power and lens choice.',
  },
  {
    id: 23,
    name: 'AquaVision Monthly',
    brand: 'Eagle Eye',
    price: 399,
    salePrice: 349,
    rating: 4.6,
    category: 'Contact Lenses',
    badge: 'Hydrating',
    image: 'https://softlenses.in/cdn/shop/files/rn-image_picker_lib_temp_0949e1cb-db1b-423f-9a0f-f099b0b50440.webp?v=1760118799',
    description: 'Monthly hydrating lenses with breathable silicone hydrogel for long-lasting clarity.',
    material: 'Silicone Hydrogel',
    color: 'Clear',
    lensWidth: '14.2mm',
    bridgeWidth: 'N/A',
    templeLength: 'N/A',
    weight: '7mg',
    warranty: '30-day satisfaction',
    priceNote: 'Price may vary based on prescription power and lens choice.',
  },
  {
    id: 24,
    name: 'Clearway Fresh',
    brand: 'Eagle Eye',
    price: 279,
    salePrice: 249,
    rating: 4.4,
    category: 'Contact Lenses',
    badge: 'Fresh',
    image: 'https://softlenses.in/cdn/shop/files/3c30feaa62728a0f4cd187ef94a9de9-900x.jpg?v=1760120137',
    description: 'Fresh daily lenses with moisture-rich comfort and breathable surface for all-day wear.',
    material: 'Hydrogel',
    color: 'Clear',
    lensWidth: '14mm',
    bridgeWidth: 'N/A',
    templeLength: 'N/A',
    weight: '6mg',
    warranty: '30-day satisfaction',
    priceNote: 'Price may vary based on prescription power and lens choice.',
  },
  {
    id: 25,
    name: 'UltraClear Pro',
    brand: 'Eagle Eye',
    price: 449,
    salePrice: 399,
    rating: 4.1,
    category: 'Contact Lenses',
    badge: 'Pro',
    image: 'https://wooeyeshop.com/cdn/shop/files/a12b6bd7cf5d61b0f83e16bb6984a926_fdc77582-3f2a-4b66-9064-b5defdedb900.jpg?v=1773383865',
    description: 'Premium silicone hydrogel lenses with enhanced oxygen flow and stable comfort.',
    material: 'Silicone Hydrogel',
    color: 'Clear',
    lensWidth: '14.5mm',
    bridgeWidth: 'N/A',
    templeLength: 'N/A',
    weight: '8mg',
    warranty: '30-day satisfaction',
    priceNote: 'Price may vary based on prescription power and lens choice.',
  },
  {
    id: 26,
    name: 'Spark Blue',
    brand: 'Eagle Eye',
    price: 299,
    salePrice: 249,
    rating: 4.4,
    category: 'Contact Lenses',
    badge: 'Blue Light',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTbSKXarHugucqUfSTQ2wZMCrUqMoqvR-JRiOYx6vKwoi2emz_REbL0L69r&s=10',
    description: 'Blue-light filtering daily lenses designed for digital comfort and reduced eye fatigue.',
    material: 'Hydrogel',
    color: 'Clear',
    lensWidth: '14mm',
    bridgeWidth: 'N/A',
    templeLength: 'N/A',
    weight: '6mg',
    warranty: '30-day satisfaction',
    priceNote: 'Price may vary based on prescription power and lens choice.',
  },
  {
    id: 27,
    name: 'Clear Day 30',
    brand: 'Eagle Eye',
    price: 339,
    salePrice: 299,
    rating: 4.3,
    category: 'Contact Lenses',
    badge: 'Monthly',
    image: 'https://img.staticdj.com/f142c6baa2389fd81d069b998860ced9_420x.jpg',
    description: '30-day wearable lenses with consistent clarity, moisture retention and hassle-free use.',
    material: 'Silicone Hydrogel',
    color: 'Clear',
    lensWidth: '14.2mm',
    bridgeWidth: 'N/A',
    templeLength: 'N/A',
    weight: '7mg',
    warranty: '30-day satisfaction',
    priceNote: 'Price may vary based on prescription power and lens choice.',
  },
  {
    id: 28,
    name: 'ActiveClear',
    brand: 'Eagle Eye',
    price: 399,
    salePrice: 349,
    rating: 3.8,
    category: 'Contact Lenses',
    badge: 'Sport',
    image: 'https://softlenses.in/cdn/shop/files/WhatsAppImage2024-10-26at9.22.35PM_31042336-f636-4b21-98fb-a27674be64f6.jpg?v=1729960677',
    description: 'Sport-fit contact lenses built for movement, breathability and secure all-day comfort.',
    material: 'Silicone Hydrogel',
    color: 'Clear',
    lensWidth: '14.3mm',
    bridgeWidth: 'N/A',
    templeLength: 'N/A',
    weight: '7mg',
    warranty: '30-day satisfaction',
    priceNote: 'Price may vary based on prescription power and lens choice.',
  },
  {
    id: 29,
    name: 'Gentle Vital',
    brand: 'Eagle Eye',
    price: 329,
    salePrice: 289,
    rating: 4.2,
    category: 'Contact Lenses',
    badge: 'Sensitive',
    image: 'https://www.specsmakers.in/cdn/shop/files/0_1_0004_GreyRevised.jpg?v=1763188828&width=1024',
    description: 'Sensitive-eye lenses with soothing hydration, gentle edges and balanced wearability.',
    material: 'Hydrogel',
    color: 'Clear',
    lensWidth: '14mm',
    bridgeWidth: 'N/A',
    templeLength: 'N/A',
    weight: '6mg',
    warranty: '30-day satisfaction',
    priceNote: 'Price may vary based on prescription power and lens choice.',
  },
  {
    id: 30,
    name: 'AquaBoost Daily',
    brand: 'Eagle Eye',
    price: 359,
    salePrice: 319,
    rating: 4.2,
    category: 'Contact Lenses',
    badge: 'Moisture',
    image: 'https://www.specsmakers.in/cdn/shop/files/Artboard1_1_168206ce-4c09-4cda-9228-8e53422f40e1.jpg?v=1763185375',
    description: 'Moisture-rich daily lenses for refreshing comfort from morning through evening.',
    material: 'Hydrogel',
    color: 'Clear',
    lensWidth: '14mm',
    bridgeWidth: 'N/A',
    templeLength: 'N/A',
    weight: '6mg',
    warranty: '30-day satisfaction',
    priceNote: 'Price may vary based on prescription power and lens choice.',
  },
  {
    id: 31,
    name: 'Mini Voyager',
    brand: 'Eagle Eye',
    price: 1199,
    salePrice: 999,
    rating: 3.7,
    category: 'Kids Glasses',
    badge: 'Kids',
    image: 'https://images.specsavers.com/glasses-images/30515475-ortho-940x529.jpg',
    description: 'A flexible kids frame with bright playful color, cushioned temples and durable everyday support.',
    material: 'Bendable Acetate',
    color: 'Coral',
    lensWidth: '46mm',
    bridgeWidth: '15mm',
    templeLength: '130mm',
    weight: '17g',
    warranty: '1 year',
    priceNote: 'Price may vary based on prescription power and lens choice.',
  },
  {
    id: 32,
    name: 'Sprout Spectrum',
    brand: 'Eagle Eye',
    price: 1299,
    salePrice: 1099,
    rating: 3.8,
    category: 'Kids Glasses',
    badge: 'Playful',
    image: 'https://www.specsmakers.in/cdn/shop/files/3_35947961-b65c-44da-921b-2a554181b0b2.jpg?v=1751350870&width=1024',
    description: 'Durable kids glasses with rounded lenses, TR90 strength and cheerful ocean blue styling.',
    material: 'TR90',
    color: 'Ocean Blue',
    lensWidth: '47mm',
    bridgeWidth: '15mm',
    templeLength: '132mm',
    weight: '18g',
    warranty: '1 year',
    priceNote: 'Price may vary based on prescription power and lens choice.',
  },
  {
    id: 33,
    name: 'BrightBeam Junior',
    brand: 'Eagle Eye',
    price: 1099,
    salePrice: 899,
    rating: 4.3,
    category: 'Kids Glasses',
    badge: 'Youth',
    image: 'https://images.specsavers.com/glasses-images/30520233-ortho-940x529.jpg',
    description: 'Lightweight kids frames with sunny accents, anti-slip nose pads and easy child-friendly wear.',
    material: 'Flexible Nylon',
    color: 'Sunshine Yellow',
    lensWidth: '45mm',
    bridgeWidth: '15mm',
    templeLength: '128mm',
    weight: '16g',
    warranty: '1 year',
    priceNote: 'Price may vary based on prescription power and lens choice.',
  },
  {
    id: 34,
    name: 'Twinkle Pop',
    brand: 'Eagle Eye',
    price: 1199,
    salePrice: 999,
    rating: 4.2,
    category: 'Kids Glasses',
    badge: 'Fun',
    image: 'https://images.specsavers.com/glasses-images/33883953-front-940x529.jpg',
    description: 'Fun kids glasses with soft hinges, bright pink tones and flexible everyday comfort.',
    material: 'TR90',
    color: 'Bubblegum Pink',
    lensWidth: '44mm',
    bridgeWidth: '15mm',
    templeLength: '127mm',
    weight: '15g',
    warranty: '1 year',
    priceNote: 'Price may vary based on prescription power and lens choice.',
  },
  {
    id: 35,
    name: 'Rocket Spark',
    brand: 'Eagle Eye',
    price: 1399,
    salePrice: 1199,
    rating: 4.2,
    category: 'Kids Glasses',
    badge: 'Adventure',
    image: 'https://image.made-in-china.com/202f0j00YvnkONbcGqko/Tr-H3612-Anti-Blue-Light-Kids-Eyeglasses-Frame-Tr90-Flexible-Kids-Eyewears.webp',
    description: 'Sport-inspired kids frames with impact-resistant build and bold blue detailing.',
    material: 'Bendable Acetate',
    color: 'Electric Blue',
    lensWidth: '47mm',
    bridgeWidth: '16mm',
    templeLength: '133mm',
    weight: '18g',
    warranty: '1 year',
    priceNote: 'Price may vary based on prescription power and lens choice.',
  },
  {
    id: 36,
    name: 'Safari Starlight',
    brand: 'Eagle Eye',
    price: 1499,
    salePrice: 1299,
    rating: 4.0,
    category: 'Kids Glasses',
    badge: 'Explorer',
    image: 'https://opticone.ae/wp-content/uploads/2023/02/Nano-flexible-glasses-optic-one-_0006_BIRDIE-NV163438-2.jpg-150x150.jpg',
    description: 'Flexible kids frames with mint green finish, silicone nose pads and active play durability.',
    material: 'Flexible Nylon',
    color: 'Mint Green',
    lensWidth: '48mm',
    bridgeWidth: '16mm',
    templeLength: '134mm',
    weight: '19g',
    warranty: '1 year',
    priceNote: 'Price may vary based on prescription power and lens choice.',
  },
  {
    id: 37,
    name: 'Galaxy Glow',
    brand: 'Eagle Eye',
    price: 1199,
    salePrice: 999,
    rating: 4.4,
    category: 'Kids Glasses',
    badge: 'Star',
    image: 'https://www.specsmakers.in/cdn/shop/files/3_8d832bba-3ec6-47b9-92a7-34878aa361e1.jpg?v=1751350875',
    description: 'Glow-in-the-dark kids glasses with playful star patterns and gentle spring hinges.',
    material: 'Flexible Nylon',
    color: 'Lilac',
    lensWidth: '45mm',
    bridgeWidth: '15mm',
    templeLength: '129mm',
    weight: '16g',
    warranty: '1 year',
    priceNote: 'Price may vary based on prescription power and lens choice.',
  },
  {
    id: 38,
    name: 'Pixie Pop',
    brand: 'Eagle Eye',
    price: 1099,
    salePrice: 899,
    rating: 4.3,
    category: 'Kids Glasses',
    badge: 'Fun',
    image: 'https://image.made-in-china.com/202f0j00FVZehgKWkvqr/Flexible-Acetate-Child-Optical-Frame-Glasses-Unbreakable-Kids-Eyewear-Anti-Blue-Light-Ages-3-12.webp',
    description: 'Colorful kids acetate frames with rounded lenses and lightweight daily comfort.',
    material: 'Acetate',
    color: 'Turquoise',
    lensWidth: '46mm',
    bridgeWidth: '15mm',
    templeLength: '131mm',
    weight: '17g',
    warranty: '1 year',
    priceNote: 'Price may vary based on prescription power and lens choice.',
  },
  {
    id: 39,
    name: 'Comet Charm',
    brand: 'Eagle Eye',
    price: 1299,
    salePrice: 1099,
    rating: 3.9,
    category: 'Kids Glasses',
    badge: 'Chic',
    image: 'https://chashmah.com/wp-content/uploads/2022/08/76007R-2.webp',
    description: 'Chic kids glasses with lavender accents, soft fit and trendy styling for school days.',
    material: 'TR90',
    color: 'Lilac',
    lensWidth: '47mm',
    bridgeWidth: '15mm',
    templeLength: '132mm',
    weight: '18g',
    warranty: '1 year',
    priceNote: 'Price may vary based on prescription power and lens choice.',
  },
  {
    id: 40,
    name: 'Buddy Blink',
    brand: 'Eagle Eye',
    price: 1199,
    salePrice: 999,
    rating: 4.2,
    category: 'Kids Glasses',
    badge: 'Adventure',
    image: 'https://static5.lenskart.com/media/catalog/product/pro/1/thumbnail/1080x1080/9df78eab33525d08d6e5fb8d27136e95//h/i/purple-full-rim-oval-kids-2-5-yrs-flexi-hooper-hp-e15972s-c2-eyeglasses_g_9077_17_08_2023.jpg',
    description: 'Bright kids frames with flexible acetate temples and lively lemon color.',
    material: 'Bendable Acetate',
    color: 'Lemon Yellow',
    lensWidth: '46mm',
    bridgeWidth: '15mm',
    templeLength: '130mm',
    weight: '17g',
    warranty: '1 year',
    priceNote: 'Price may vary based on prescription power and lens choice.',
  },
]
